package main.java.socket;

public enum Requests {
    REGISTER("REGISTER"),
    LOGIN("LOGIN"),
    GET_QUESTIONS("GET_QUESTIONS"),
    ACCEPT("ACCEPT"),
    FALSE("FALSE"),
    WAIT_FOR_OTHER_PLAYER("WAIT_FOR_OTHER_PLAYER"),
    LOG_OUT("LOG_OUT"),
    OUT_OF_MULTIPLAYER("OUT_OF_MULTIPLAYER"),
    SEND_SELECTED_CATEGORY("SEND_SELECTED_CATEGORY"),
    GET_QUESTION("GET_QUESTION"),
    UPDATE_SCORES("UPDATE_SCORES"),
    SET_USER("SET_USER"),
    GET_FINAL_SCORE("GET_FINAL_SCORE"),
    EXIT_MULTIPLAYER_AFTER_GAME("EXIT_MULTIPLAYER_AFTER_GAME"),
    ENTERED_CHET_ROOM("ENTERED_CHET_ROOM"),
    OUT_OF_CHET_ROOM("OUT_OF_CHET_ROOM");

    public String request;

    Requests(String request) {
        this.request = request;
    }
}
